### ISSUE TITLE
Impossible to rename the Dropbox folder

### ISSUE THREAD

**Issue by felagund** [dropbox/nautilus-dropbox#10]
I do not want to have a folder named Dropbox on my system. I cannot rename it. I am sure you tihnk that it is great marketing or something, but it is not, I like Dropbox because it works well, not because it forces me to have a folder named "Dropbox" on my system.

**Comment by lfaraone** [comment]
This bug is related to the proprietary daemon, not `nautilus-dropbox`.

Support for the Dropbox product ifself is available at https://www.dropbox.com/support/.
