### ISSUE TITLE
Does not work on Gnome 43 (e.g. Fedora 37, Ubuntu 22.10)

### ISSUE THREAD

**Issue by exterm** [dropbox/nautilus-dropbox#108]
As foreshadowed by https://github.com/dropbox/nautilus-dropbox/issues/101 and https://github.com/dropbox/nautilus-dropbox/pull/105, nautilus-dropbox does not work with current versions of Gnome anymore. This means it doesn't work with current versions of Fedora or Ubuntu.

The reason is a dependency on an outdated (and now removed) version of libnautilus-extension. `libnautilus-extension.so.1`.

There is a [thread on the dropbox forums about this](https://www.dropboxforum.com/t5/Apps-and-Installations/cannot-install-on-Linux-Fedora-37/td-p/632084) too, with added details, as well as a [thread on the Fedora forums](https://ask.fedoraproject.org/t/official-dropbox-package-doesnt-install-in-fedora-37/27296).

Please fix this soon, as otherwise most linux users will not be able to easily use dropbox anymore (assuming most Linux users use Gnome and nautilus and will migrate to Gnome >=43 some time soon).

**Comment by exterm** [comment]
@goffrie Anything you can do about this?

**Comment by chomskysfavefive** [comment]
I just built it with the recent fix, and it seems to be working great.

**Comment by exterm** [comment]
So all we need is a new release now.

**Comment by goffrie** [comment]
A new release has been cut (nominally version 2022.12.05) and https://www.dropbox.com/install-linux was updated as of last Thursday.

**Comment by goffrie** [comment]
(Also, we're aiming to improve our process so that we can get a faster turnaround in the future!)
