### ISSUE TITLE
Allow several folders to by synced without them having to be put or linked to "Dropbox" folder

### ISSUE THREAD

**Issue by felagund** [dropbox/nautilus-dropbox#11]
I want to have several folders synced. Now the application makes me to 
1) put them to Dropbox folder - which I do not want, they have a place in my filesystem hierachy that makes sense to me and I have no idea why I should change that because of some cloud service
2) link them from the Dropbxo folder, which leads to https://github.com/dropbox/nautilus-dropbox/issues/9 - if that were fixed and https://github.com/dropbox/nautilus-dropbox/issues/10 were fixed, I could just make a hidden ~/.dropbox/dropbox_wont_sync_several_folders_without_a_master_folder (or appropriate location if https://github.com/dropbox/nautilus-dropbox/issues/5 were fixed) and link those folders I want to sync, but it would be nice if I did not have to "hack" the dropbox application in this way and it would just expose this in its setting. I cannot be that hard, or am I mistaken?

**Comment by lfaraone** [comment]
This bug is related to the proprietary daemon, not `nautilus-dropbox`.

Support for the Dropbox product ifself is available at https://www.dropbox.com/support/.
