### ISSUE TITLE
Unknown icon showing for shared folders

### ISSUE THREAD

**Issue by belegdol** [dropbox/nautilus-dropbox#111]
> > On Fedora 37 there is an unknown icon showing for folders containing images: ![Bildschirmfoto vom 2022-11-15 19-22-02](https://user-images.githubusercontent.com/1208329/201996966-d7fffdce-6e73-4af3-aa92-56096d05a96c.png)
> 
> This is because the dropbox backend is sending a bad emblem name to nautilus-dropbox. Here's a workaround, it's ugly, so I don't really want to include it in this PR
> 
> ```
> diff --git a/src/nautilus-dropbox.c b/src/nautilus-dropbox.c
> index b9c10b4..e1a1d0f 100644
> --- a/src/nautilus-dropbox.c
> +++ b/src/nautilus-dropbox.c
> @@ -361,7 +361,12 @@ nautilus_dropbox_finish_file_info_command(DropboxFileInfoCommandResponse *dficr)
>        int i;
>        for ( i = 0; status[i] != NULL; i++) {
>           if (status[i][0])
> -           nautilus_file_info_add_emblem(dficr->dfic->file, status[i]);
> +         {
> +           gchar *emblem = status[i];
> +           if (g_strcmp0(emblem, "people") == 0)
> +             emblem = "shared";
> +           nautilus_file_info_add_emblem(dficr->dfic->file, emblem);
> +         }
>        }
>        result = NAUTILUS_OPERATION_COMPLETE;
>      }
> ```

Thanks for pointing this out. I'll get a fix for this into the next release of the client.

_Originally posted by @goffrie in https://github.com/dropbox/nautilus-dropbox/issues/105#issuecomment-1331363669_

This is still an issue in 2022.12.05, can be fixed with the mentioned hack.

**Comment by goffrie** [comment]
The bad emblem name lives in the (closed-source) desktop client, rather than nautilus-dropbox. It's fixed in version 164, [which is currently available in beta](https://www.dropboxforum.com/t5/Dropbox-desktop-client-builds/Beta-Build-164-3-7907/td-p/644529); due to holiday season release slowdowns it won't make it into the stable build until the new year.

**Comment by belegdol** [comment]
I can confirm this is fixed as of 172.4.7555.
