### ISSUE TITLE
No tray icon is sytem tray

### ISSUE THREAD

**Issue by Yanpas** [dropbox/nautilus-dropbox#12]
There is no dropbox in tray when I suspend my notebook via closing lid. But dropbox works itself.

Is dropbox tray icon QT5 default or self-written?
Linux 3.16 Ubuntu 14.04

**Comment by Yanpas** [comment]
HEEEY! ANYBODY ALIVE ON THIS GITHUB?
Here is a video of your buggy tray icon https://youtu.be/bbEAJxqd_Rc
Telegram, which uses QT tray icon too don't have such a problem. Try updating QT

**Comment by euresti** [comment]
This is a dropbox error, not a nautilus-dropbox error.  Feel free to bring it up in https://www.dropboxforum.com/hc/en-us/community/topics/200210355-Desktop-Client-Builds?sort_by=recent_activity
