### ISSUE TITLE
Tagging new release that is said in configure.ac and ChangeLog

### ISSUE THREAD

**Issue by sjp760** [dropbox/nautilus-dropbox#129]
The latest tagged release on github is v2020.03.04 while in configure.ac and ChangeLog it says v2023.09.06. Is it possible to tag the new release on github for distros to use?

**Comment by jewelpit** [comment]
Oop, here you go: https://github.com/dropbox/nautilus-dropbox/releases/tag/v2023.09.06. Sorry about that!
