### ISSUE TITLE
Dropbox right click menu - Reference Center (or help) error

### ISSUE THREAD

**Issue by Yanpas** [dropbox/nautilus-dropbox#14]
If I right click and click Refference Center- i get three errors in thunar:
Can't open «/tmp/dbxlzimoON.html#e33195909563b4a0efe3902199b5f570b49cbff95f2cb45a03db67851c7ef85c6586d6b467e2b6bef2b37c».
Can't open 
/tmp/dbxlCHF1ym.html#a8eca305bbf4db9b043a32b0f6386f9e88fdd50783922ed24dde6137d421fc647bfa7915c815c10acece02
Can't open /tmp/dbxlzimoON.html#e33195909563b4a0efe3902199b5f570b49cbff95f2cb45a03db67851c7ef85c6586d6b467e2b6bef2b37c».
Input output error

**Comment by euresti** [comment]
This is a dropbox error, not a nautilus-dropbox error.  Feel free to bring it up in https://www.dropboxforum.com/hc/en-us/community/topics/200210355-Desktop-Client-Builds?sort_by=recent_activity
