### ISSUE TITLE
Official Ubuntu build uninstallable on 24.04 Noble

### ISSUE THREAD

**Issue by yfreund** [dropbox/nautilus-dropbox#141]
Noble isn't even in beta yet, but since you're already providing packages for it in your [official repo](https://linux.dropboxstatic.com/ubuntu/dists/noble/), and since the fix seems to be persistent across older versions as well, I figured I should already create this bug report.

The build seems to depend on `libpango1.0-0 (>= 1.36.3)`, which has been set as a transitional package since Jammy (22.04) and has now been completely removed. It should probably depend on `libpango-1.0-0` instead (notice the extra dash), or perhaps [one of the other packages the transitional package provides](https://packages.ubuntu.com/jammy/libpango1.0-0), e.g. `libpangocairo-1.0-0`.

AFAICT this change should be done [here](https://github.com/dropbox/nautilus-dropbox/blob/master/generate-deb.sh#L427).

**Comment by yfreund** [comment]
Looks like this has been a problem for a while on Debian as well - #95

**Comment by jewelpit** [comment]
Oops, I'll fix this today.

**Comment by yfreund** [comment]
@jewelpit Thanks for the fix - this should probably do the trick once a new version is released.

I should point out that the package hasn't been renamed, rather split up into different packages - the deprecated meta-package `libpango1.0-0` and the package `libpango-1.0-0` do not have the same content/dependencies. I did a quick check (on holiday with limited internet access at the moment), and any missing dependencies should be covered by `gir1.2-pango-1.0`.

It might be worthwhile to clean up the build process in the future, in order to avoid unnecessary/duplicate dependencies.
