### ISSUE TITLE
Unable to install due to Python 2/3 versions problems

### ISSUE THREAD

**Issue by SilverBut** [dropbox/nautilus-dropbox#16]
Under distributions based on Python 3 instead of 2, this problem may happen:

``` shell
checking for python... /usr/bin/python2
checking for rst2man... python rst2man.py
checking for pygtk... no
configure: error: couldn't find pygtk
```

Even if you've already ran this command, the error is still here:

``` shell
pip2 install pygtk
```

The problem is `configure` script used these code to detect if pygtk is available:

``` shell
cat <<EOF | python
try:
 import gtk
except:
 exit(1)
else:
 exit(0)
EOF
```

(Line 10802)

If the system is based on python 2, it will stuck.

Besides, some other scripts will not work if you don't re-edit their hash-bang from `/usr/bin/python` to `/usr/bin/python2`.

The easiest way is to run this vim command on each file:

``` vim
:1,$s/python/python2/g
```

However, upgrading to Python 3 is a good idea, to make it faster and better.

Thanks.

**Comment by lfaraone** [comment]
Distributions changing `/usr/bin/python` to Python 2.x is not supported.
