### ISSUE TITLE
Not syncing anymore

### ISSUE THREAD

**Issue by zeenix** [dropbox/nautilus-dropbox#19]
Hi,

Seems that new content added to my DropBox area don't appear anymore in Nautilus view. I have tried refreshing with F5 key but no luck. I know another user who observed the same recently.

I'm using nautilus-dropbox-2015.10.28-1.fc10.x86_64 package on my Fedora 24 host.

**Comment by StupeFat** [comment]
I had the same problem, I just solved by using the following command line:

dropbox stop && dbus-launch dropbox start

(source: the www)

**Comment by lfaraone** [comment]
This bug is related to the proprietary daemon, not `nautilus-dropbox`.

Support for the Dropbox product itself is available at https://www.dropbox.com/support/.
