### ISSUE TITLE
"Dropbox needs to fix permissions"

### ISSUE THREAD

**Issue by johnlevon** [dropbox/nautilus-dropbox#23]
[moz@pent ~]$ rpm -q dropbox
dropbox-2.10.0-3.fc24.noarch

[moz@pent ~]$ ls -dl Dropbox/
drwx------. 11 moz moz 4096 Aug 18 11:07 Dropbox/

I get dropbox often popping up and claiming it needs to "fix permissions" on the Dropbox/ directory, and asking for a password. It doesn't explain what that means, and as far as I can see, there are no permissions problems here.

**Comment by lfaraone** [comment]
This message is generated by the proprietary daemon, not this software.

Support for the Dropbox product ifself is available at https://www.dropbox.com/support/.
