### ISSUE TITLE
dropbox.com/install-linux deb installs willy version on xenial

### ISSUE THREAD

**Issue by robkorv** [dropbox/nautilus-dropbox#27]
Don't know if this is the right place for this, please point me in the right direction if it isn't.

When I install the deb package from https://www.dropbox.com/install-linux it creates a `/etc/apt/sources.list.d/dropbox.list` with `deb [arch=i386,amd64] http://linux.dropbox.com/ubuntu wily main` as content.

This also happened two year ago when I installed it on Trusty. I think this is a packaging bug or the version on https://www.dropbox.com/install-linux should be updated, it points to https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2015.10.28_amd64.deb.

**Comment by robkorv** [comment]
The content of `/etc/apt/sources.list.d/dropbox.list` should be `deb [arch=i386,amd64] http://linux.dropbox.com/ubuntu trusty main` on Trusty and `deb [arch=i386,amd64] http://linux.dropbox.com/ubuntu xenial main`

**Comment by lfaraone** [comment]
The built package is the same across all distros -- this doesn't actually have an impact on the system, although it'd be nice for it to be correct.
