### ISSUE TITLE
Fedora 27 Repo

### ISSUE THREAD

**Issue by antokara** [dropbox/nautilus-dropbox#41]
Just upgraded to Fedora 27 from Fedora 26 and there is no
https://linux.dropbox.com/fedora/27/
Please add it when possible.

For anyone else having issues installing Dropbox on Fedora 27, you could try:
`$sudo vi /etc/yum.repos.d/dropbox.repo`
and replacing
`baseurl=http://linux.dropbox.com/fedora/$releasever/`
to
`baseurl=http://linux.dropbox.com/fedora/26/`
I believe, this should work as a temporary workaround...

**Comment by antokara** [comment]
I am not sure if this is the correct repository to open this issue
or I should just go to https://www.dropboxforum.com/ and report it there.
So, I am closing this issue and if someone thinks otherwise, please re-open.

**Comment by mmrezaie** [comment]
Why is this issue not getting a fix? is Dropbox going to stop adding support for the newer releases of Fedora?

**Comment by ttynjala** [comment]
Looks like its time to start drawing conclusions about the dropbox commitment to Linux. Fc28 is out and not even fc27 is supported.

**Comment by nipunn1313** [comment]
Hi - I've added 27 and 28 to the page. Let me know if there are any issues.

I'll close out this issue for now - please reopen if there's an issue.
Thank you!

**Comment by aLoneStrider** [comment]
Hi @nipunn1313,
Fedora 29 is out and there's no repository for it. 
I'll open the issue to update the repositories.

Thanks

**Comment by nipunn1313** [comment]
Filed #60 to track
