### ISSUE TITLE
Install instructions don't work

### ISSUE THREAD

**Issue by SebStaeubert** [dropbox/nautilus-dropbox#43]
Hi,
the description you provide in INSTALL does not work. The script "configure" does not exist.
You also give a hint to autoconf but do not provide any advice howto use it.
I tried simply running autoconf in the cloned repository and got the following error message:
> autoconf
configure.in:5: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.in:9: error: possibly undefined macro: AM_CONFIG_HEADER
configure.in:20: error: possibly undefined macro: AM_PROG_LIBTOOL
configure.in:76: error: possibly undefined macro: AM_CONDITIONAL

Could you please a working howto?

THX

**Comment by GLolol** [comment]
Try running `./autogen.sh` and then configure

**Comment by SebStaeubert** [comment]
THX. It would be nice to provide this hint in the howto.

**Comment by samertm** [comment]
I updated the instructions in README.md to specify that you need to run autogen.sh. Thanks for using Dropbox!
