### ISSUE TITLE
./configure complains. gdebi refuses to install. Kinda like issue #43

### ISSUE THREAD

**Issue by RickyS** [dropbox/nautilus-dropbox#48]
## Q: Is it possible to install both the main Dropbox app and also nautilus-dropbox? Apparently not!
Description:	Ubuntu 18.04 LTS
Codename:	bionic
Linux Who 4.15.0-23-generic #25-Ubuntu SMP Thu May 31 16:36:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
buster/sid
```
 $ nautilus --version                                                                                        ———
Initializing nautilus-dropbox 2015.10.28
GNOME nautilus 3.26.3
 
$ gnome-shell --version                                                                                     ———
GNOME Shell 3.28.1

```
I have nautilus-dropbox installed and running. I tried to install the main Dropbox app, got some trouble, assumed it must be I have an old version of something, and tried installing new stuff. 

Trying to build. Figured out to run autogen.sh. ./configure then said:
```
checking for NAUTILUS... no
configure: error: Package requirements (libnautilus-extension >= 2.16.0) were not met:

No package 'libnautilus-extension' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables NAUTILUS_CFLAGS
and NAUTILUS_LIBS to avoid the need to call pkg-config.
```
I do have earlier versions:
lrwxrwxrwx 1 root root    30 Apr 20 18:39 /usr/lib/x86_64-linux-gnu/libnautilus-extension.so.1 -> libnautilus-extension.so.1.4.0
-rw-r--r-- 1 root root 38824 Apr 20 18:39 /usr/lib/x86_64-linux-gnu/libnautilus-extension.so.**1.4.0**

-----------------------
So I set:
  NAUTILUS_LIBS=/usr/lib/x86_64-linux-gnu/:/usr/lib/x86_64-linux-gnu/nautilus/extensions-3.0/
And tried again. ./configure made the same complaint, no doubt because my version number of the library is too low.

===============================
 I wanted to install the main Dropbox application as described in [this article](https://www.nytimes.com/2016/12/23/technology/personaltech/the-art-of-the-selective-dropbox-sync.html?mabReward=CTM&recp=0&moduleDetail=recommendations-0&action=click&contentCollection=Well&region=Footer&module=WhatsNext&version=WhatsNext&contentID=WhatsNext&src=recg&pgtype=article).

So I downloaded the .deb file and got this:
```
 $ sudo gdebi dropbox_2015.10.28_amd64.deb                                                                   ———
Reading package lists... Done
Building dependency tree        
Reading state information... Done
Reading state information... Done
This package is uninstallable
Breaks existing package 'nautilus-dropbox' conflict: dropbox ( )
```
================
Getting desperate, I even tried installing the library:
```
 $ sudo  apt-get install libnautilus-extension-dev                                           ———

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libnautilus-extension-dev : Depends: libgtk-3-dev (>= 3.22.6) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

```

So I'm giving up for now. Any and all suggesions are welcome. Especially those that work...

**Comment by samertm** [comment]
This issue was caused by launching dropbox with `dbus-launch`. This has been fixed, since we've reverted that diff.
