### ISSUE TITLE
nautilus-dropbox ships configure.in

### ISSUE THREAD

**Issue by Zlogene** [dropbox/nautilus-dropbox#50]
Not really nice thingy, It is obsolete and not recomended, could you please use `configure.ac` please?

**Comment by nipunn1313** [comment]
Hi - thanks for the report! We'll keep this in mind as we update the installation instructions. This seems like an easy rename, correct? If you send a PR with the rename + updated version number instructions for autoconf, that would be great.

**Comment by samertm** [comment]
Done in 8f7bea456dfbbd55aa8d19efdd8208fb3336fbed. Thanks for the report!
