### ISSUE TITLE
nautilus-dropbox uses obsolete python-gpgme

### ISSUE THREAD

**Issue by dgtombs** [dropbox/nautilus-dropbox#51]
nautilus-dropbox uses python-gpgme to verify signatures, but that Python module is now obsolete. It was [removed from Debian in October 2017](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=876844) and therefore is now gone from Ubuntu as well.

The impact of this bug is that nautilus-dropbox can't verify signatures on recent versions of Debian and Ubuntu, and perhaps other platforms as well.

## Solution info

Per the linked bug, Debian (and Ubuntu) now include a python-gpg package that effectively replaces python-gpgme. This new package is actually from gpgme upstream, unlike python-gpgme.

Please see [this similar issue](https://salsa.debian.org/qa/distro-tracker/issues/2) for an example and more info.

**Comment by nipunn1313** [comment]
Thanks for the report! This seems important and a relatively easy fix. I'll file something internally to take a look. Pull requests are always welcome!

**Comment by samertm** [comment]
Thanks for the report! I fixed it in e9367206f9b723103362e8dd154363517e9a9841.
