### ISSUE TITLE
Ubuntu 18.04.1 LTS - doesn't link to dropbox acct (plus no status icons etc)

### ISSUE THREAD

**Issue by jmarshallnz** [dropbox/nautilus-dropbox#53]
There seems to be a bunch of issues with dropbox on a Ubuntu 18.04.1 LTS clean install.

### From Ubuntu repo

Installing from the Ubuntu repo results in the usual install process going fine. On start of Dropbox it complains about python-gpgme being missing (as it's no longer in the Ubuntu repository), but otherwise downloads the linux distro and extracts as expected.

However it does not load the webbrowser to link to an account.

Running dropbox status from Terminal shows it is running and 'Waiting to be linked to a Dropbox account...'. No link is given, and there's no app icon or anything running (not sure if this is a gnome issue?)

### From github

Builds and installs fine. No longer complains about python-gpgme as it was fixed in #51 :) Still does not fire up a browser for linking the account.

Running dropbox status from Terminal shows it is running and 'Waiting to be linked to a Dropbox account...' But, the link URL is given! Yay! Opening the link then allows linking the computer to the account.

HOWEVER: Dropbox on the machine does not update from this state. It is still 'Waiting to be linked to a Dropbox account...'

Again, no app icon in system tray or anything like that.

Am happy to supply logs etc as needed - just let me know what you need.

**Comment by nipunn1313** [comment]
Hi - thanks for reaching out. We'll take a look and see if we can reproduce.

**Comment by jmarshallnz** [comment]
Thanks for the response :)

Have reinstalled nautilus-dropbox fresh from source. Unfortunately nothing in those folders (i.e. empty log/0/ and log/1/ folders) as yet. Will leave it for day or two and see if a log file shows up. If I load the current URL specified in the "To link this computer to a dropbox account" it states that "This computer is already linked to a Dropbox account." which makes sense (I already clicked on the previous one) yet dropbox status continues to say it's unlinked. No dropbox icons or dropbox folder created etc.

Note that I'm running 18.04.1, not 18.04. Am not sure if this will make a difference or not.
