### ISSUE TITLE
Please port to python3

### ISSUE THREAD

**Issue by raveit65** [dropbox/nautilus-dropbox#55]
Fedora will switch to python3 with fedora 30.

Fedora 30 System-Wide Change proposal: Mass Python 2 Package Removal
https://fedoraproject.org/wiki/Changes/Mass_Python_2_Package_Removal

https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/QRXWWZ2QG7JSZMAXNI6M6QMWV2XPCINM/

At this time we can't build nautilus-dropbox and the subpackages for caja- and nemo-file-browser at rpmfusion build-servers for fedora any more.
Of course your own builds for fedora won't work with fedora 30.
Currently fedora 29 is branched from fedora rawhide branch. That means building nautilus-dropbox at master branch for rpmfusion stopped working now.

Upstream report:
https://bugzilla.rpmfusion.org/show_bug.cgi?id=5014

Please port to python3.

Best regards

**Comment by nipunn1313** [comment]
Hi - thanks for the report. I'll file something internally.

**Comment by raveit65** [comment]
Thanks,
f30 beta freeze is at 2019-03-05 https://fedoraproject.org/wiki/Releases/30/Schedule
But python3 will be removed earlier from build-servers, probably when f30 will be branched from rawhide branch.

**Comment by monsta** [comment]
Ok, this is almost done by now... what's left is porting `rst2man.py`.

**Comment by raveit65** [comment]
I know that isn't related to nautilus-dropbox but why dropbox writes (non-error-messages) to `.xsession-errors` log without reason?
```
dropbox: locating interpreter
dropbox: logging to /tmp/dropbox-antifreeze-YhY4OU
dropbox: initializing
dropbox: initializing python 3.6.7
dropbox: setting program path '/home/rave/.dropbox-dist/dropbox-lnx.x86_64-66.3.77/dropbox'
dropbox: setting home path '/home/rave/.dropbox-dist/dropbox-lnx.x86_64-66.3.77'
dropbox: setting python path '/home/rave/.dropbox-dist/dropbox-lnx.x86_64-66.3.77:/home/rave/.dropbox-dist/dropbox-lnx.x86_64-66.3.77/python-packages-36.zip'
dropbox: python initialized
dropbox: running dropbox
dropbox: setting args
dropbox: applying overrides
dropbox: running main script
dropbox: load fq extension '/home/rave/.dropbox-dist/dropbox-lnx.x86_64-66.3.77/cryptography.hazmat.bindings._constant_time.cpython-36m-x86_64-linux-gnu.so'
dropbox: load fq extension '/home/rave/.dropbox-dist/dropbox-lnx.x86_64-66.3.77/cryptography.hazmat.bindings._openssl.cpython-36m-x86_64-linux-gnu.so'
dropbox: load fq extension '/home/rave/.dropbox-dist/dropbox-lnx.x86_64-66.3.77/cryptography.hazmat.bindings._padding.cpython-36m-x86_64-linux-gnu.so'
dropbox: load fq extension '/home/rave/.dropbox-dist/dropbox-lnx.x86_64-66.3.77/psutil._psutil_linux.cpython-36m-x86_64-linux-gnu.so'
dropbox: load fq extension '/home/rave/.dropbox-dist/dropbox-lnx.x86_64-66.3.77/psutil._psutil_posix.cpython-36m-x86_64-linux-gnu.so'
dropbox: load fq extension '/home/rave/.dropbox-dist/dropbox-lnx.x86_64-66.3.77/linuxffi.pthread._linuxffi_pthread.cpython-36m-x86_64-linux-gnu.so'
dropbox: load fq extension '/home/rave/.dropbox-dist/dropbox-lnx.x86_64-66.3.77/tornado.speedups.cpython-36m-x86_64-linux-gnu.so'
dropbox: load fq extension '/home/rave/.dropbox-dist/dropbox-lnx.x86_64-66.3.77/dbxlog._dbxlog.cpython-36m-x86_64-linux-gnu.so'
dropbox: load fq extension '/home/rave/.dropbox-dist/dropbox-lnx.x86_64-66.3.77/cpuid.compiled._cpuid.cpython-36m-x86_64-linux-gnu.so'
dropbox: load fq extension '/home/rave/.dropbox-dist/dropbox-lnx.x86_64-66.3.77/linuxffi.resolv.compiled._linuxffi_resolv.cpython-36m-x86_64-linux-gnu.so'
dropbox: load fq extension '/home/rave/.dropbox-dist/dropbox-lnx.x86_64-66.3.77/linuxffi.gnu.compiled._linuxffi_gnu.cpython-36m-x86_64-linux-gnu.so'
dropbox: load fq extension '/home/rave/.dropbox-dist/dropbox-lnx.x86_64-66.3.77/linuxffi.sys.compiled._linuxffi_sys.cpython-36m-x86_64-linux-gnu.so'
dropbox: load fq extension '/home/rave/.dropbox-dist/dropbox-lnx.x86_64-66.3.77/librsyncffi.compiled._librsyncffi.cpython-36m-x86_64-linux-gnu.so'
dropbox: load fq extension '/home/rave/.dropbox-dist/dropbox-lnx.x86_64-66.3.77/posixffi.libc._posixffi_libc.cpython-36m-x86_64-linux-gnu.so'
dropbox: load fq extension '/home/rave/.dropbox-dist/dropbox-lnx.x86_64-66.3.77/PyQt5.QtCore.cpython-36m-x86_64-linux-gnu.so'
dropbox: load fq extension '/home/rave/.dropbox-dist/dropbox-lnx.x86_64-66.3.77/PyQt5.QtGui.cpython-36m-x86_64-linux-gnu.so'
dropbox: load fq extension '/home/rave/.dropbox-dist/dropbox-lnx.x86_64-66.3.77/PyQt5.QtNetwork.cpython-36m-x86_64-linux-gnu.so'
dropbox: load fq extension '/home/rave/.dropbox-dist/dropbox-lnx.x86_64-66.3.77/PyQt5.QtWidgets.cpython-36m-x86_64-linux-gnu.so'
dropbox: load fq extension '/home/rave/.dropbox-dist/dropbox-lnx.x86_64-66.3.77/PyQt5.QtWebKit.cpython-36m-x86_64-linux-gnu.so'
dropbox: load fq extension '/home/rave/.dropbox-dist/dropbox-lnx.x86_64-66.3.77/PyQt5.QtWebKitWidgets.cpython-36m-x86_64-linux-gnu.so'
dropbox: load fq extension '/home/rave/.dropbox-dist/dropbox-lnx.x86_64-66.3.77/PyQt5.QtPrintSupport.cpython-36m-x86_64-linux-gnu.so'
dropbox: load fq extension '/home/rave/.dropbox-dist/dropbox-lnx.x86_64-66.3.77/PyQt5.QtDBus.cpython-36m-x86_64-linux-gnu.so'
```

**Comment by samertm** [comment]
This is now completely done as of https://github.com/dropbox/nautilus-dropbox/commit/895e1323a815818944bbbb38ee75a13785c1a013

@raveit65 those are the logs that dropbox writes to stdout. I can update dropbox so it's silent by default on startup unless there's a certain environmental variable set. Is there a standard for env vars like that? Otherwise I'll use `DROPBOX_STARTUP_VERBOSE=1`. (Closing the issue since this is unrelated, but feel free to reply on this issue.)

**Comment by raveit65** [comment]
@samertm 
First, Thanks for the new release.
Those logs doesn't belongs in ~/.xsession-errors because they are not error logs.
Normal run time log messages shouldn't spam an error log.

Maybe you like to have a fix for using python2-doc-utils?
I can do a PR with that code from our fork caja-dropbox?
https://github.com/mate-desktop/caja-dropbox/commit/3d48c5e516b5c1ab5d68def01ee5e8d9ad1df893

Also , is there a chance to add file-browser extension code for caja and nemo filebrowser, to avoid code duplication?
See what we do at rpmfusion for fedora.
Here only nautilus-dropbox ships the dropbox binary and /usr/share/ dir.
http://pkgs.rpmfusion.org/cgit/nonfree/nautilus-dropbox.git/tree/nautilus-dropbox.spec#n59
For caja-dropbox and nemo-dropbox we delete the binary during rpm building, and both packages simply requires nautilus-dropbox.
http://pkgs.rpmfusion.org/cgit/nonfree/caja-dropbox.git/tree/caja-dropbox.spec#n28
http://pkgs.rpmfusion.org/cgit/nonfree/caja-dropbox.git/tree/caja-dropbox.spec#n51
(same for nemo-dropbox at rpmfusion)
In result all 3 packages can be installed together and don't create a file conflict.
Caja and nemo are forks from nautilus for MATE and Cinnamon desktop.

**Comment by monsta** [comment]
Fixes for docutils stuff are already here, https://github.com/dropbox/nautilus-dropbox/commit/3ec3a5c0ebafffdd8aaae812d9586941328e600e and https://github.com/dropbox/nautilus-dropbox/commit/7cfb92a2b428ed6db098c18c991b1b904f04bf5a.
