### ISSUE TITLE
Installer should suggest python3-gpg, not python-gpg

### ISSUE THREAD

**Issue by bchallenor** [dropbox/nautilus-dropbox#72]
The installer gives this suggestion:

> Note: python-gpg (python-gpgme for Ubuntu 16.10 and lower) is not installed, we will not be able to verify binary signatures.

However, installing python-gpg does not fix this. The correct dependency seems to be python3-gpg, now that the script uses python3.

**Comment by samertm** [comment]
Thanks for the report! I've already fixed this in 6d07afce69aba4eaefb8c8dbec12747322022716, but I need to do a release. I'll get to that soon.
