### ISSUE TITLE
Web User Interface Bug

### ISSUE THREAD

**Issue by Donboscow** [dropbox/nautilus-dropbox#74]
After installing Dropbox on Ubuntu It's open a dropbox link in web browser to let the user "Sign in or create an account" then connect the computer with Dropbox. But the problem is this particular page has no "Sign in with Google" option. This page is missing the feature.

![Screenshot from 2019-05-17 02-04-02](https://user-images.githubusercontent.com/44976018/57887178-b3287280-7850-11e9-89c3-c249c5303468.png)

But the dropbox.com homepage has particular option like its android app. It's very important because lots of user sign up & sign in dropbox with Google.

**Comment by lfaraone** [comment]
Hi! This is for bugs in the `nautilus-dropbox` shell extension itself. For server-side issues, please see https://www.dropbox.com/support

(although, note that you can also just log in to the website with Google normally, then relink your client)
