### ISSUE TITLE
Please provide repo for Fedora 30

### ISSUE THREAD

**Issue by lucassantosninb** [dropbox/nautilus-dropbox#76]
There is no repository for Fedora 30.

![https_linux-dropbox-com_fedora](https://user-images.githubusercontent.com/5558472/59650079-22003080-915b-11e9-8e40-747589ecb2b0.png)

```
$ cat /etc/yum.repos.d/dropbox.repo 
[Dropbox]
name=Dropbox Repository
baseurl=http://linux.dropbox.com/fedora/$releasever/
gpgkey=https://linux.dropbox.com/fedora/rpm-public-key.asc
```

**Comment by nipunn1313** [comment]
Thanks for the report! Looking at it!

**Comment by nipunn1313** [comment]
Resolved!
