### ISSUE TITLE
Dropbox stuck on syncing 15 files taking 100% CPU all the time

### ISSUE THREAD

**Issue by kub1x** [dropbox/nautilus-dropbox#81]
Hey, 
I've had several versions of dropbox and all had the same issue. There are 15 files Dropbox just won't sync yet it takes 100% CPU all the time. It's been many weeks like this. All other files sync fine but it always go back to the last 15 files. 

![screen-2019-12-03-23-54-47](https://user-images.githubusercontent.com/1833840/70394658-61ffec00-19f7-11ea-8574-b812cfd7eb90.png)

Follows complete information I have at the moment. 
I'd gladly provide more, but don't know how to investigate deeper into the issue. 
How do I see what files is Dropbox syncing? 
How do I explore the binary log files in `~/.dropbox/logs/`? 
Or is there anywhere else to look? 
The file in `/tmp/` has no more info in it. Nothing in `/var/log/` either. 

```
~ $ dropbox start
Starting Dropbox...dropbox: locating interpreter
dropbox: logging to /tmp/dropbox-antifreeze-TVKoTW
dropbox: initializing
dropbox: initializing python 3.7.2
dropbox: setting program path '/opt/dropbox/dropbox'
dropbox: setting home path '/opt/dropbox'
dropbox: setting python path '/opt/dropbox:/opt/dropbox/python-packages-37.zip'
dropbox: python initialized
dropbox: running dropbox
dropbox: setting args
dropbox: applying overrides
dropbox: running main script
dropbox: load fq extension '/opt/dropbox/cryptography.hazmat.bindings._constant_time.cpython-37m-x86_64-linux-gnu.so'
dropbox: load fq extension '/opt/dropbox/cryptography.hazmat.bindings._openssl.cpython-37m-x86_64-linux-gnu.so'
dropbox: load fq extension '/opt/dropbox/cryptography.hazmat.bindings._padding.cpython-37m-x86_64-linux-gnu.so'
dropbox: load fq extension '/opt/dropbox/psutil._psutil_linux.cpython-37m-x86_64-linux-gnu.so'
dropbox: load fq extension '/opt/dropbox/psutil._psutil_posix.cpython-37m-x86_64-linux-gnu.so'
dropbox: load fq extension '/opt/dropbox/linuxffi.pthread._linuxffi_pthread.cpython-37m-x86_64-linux-gnu.so'
dropbox: load fq extension '/opt/dropbox/cpuid.compiled._cpuid.cpython-37m-x86_64-linux-gnu.so'
dropbox: load fq extension '/opt/dropbox/apex._apex.cpython-37m-x86_64-linux-gnu.so'
dropbox: load fq extension '/opt/dropbox/tornado.speedups.cpython-37m-x86_64-linux-gnu.so'
dropbox: load fq extension '/opt/dropbox/linuxffi.resolv.compiled._linuxffi_resolv.cpython-37m-x86_64-linux-gnu.so'
dropbox: load fq extension '/opt/dropbox/librsyncffi.compiled._librsyncffi.cpython-37m-x86_64-linux-gnu.so'
dropbox: load fq extension '/opt/dropbox/linuxffi.sys.compiled._linuxffi_sys.cpython-37m-x86_64-linux-gnu.so'
dropbox: load fq extension '/opt/dropbox/posixffi.libc._posixffi_libc.cpython-37m-x86_64-linux-gnu.so'
dropbox: load fq extension '/opt/dropbox/linuxffi.gnu.compiled._linuxffi_gnu.cpython-37m-x86_64-linux-gnu.so'
dropbox: load fq extension '/opt/dropbox/PyQt5.QtCore.cpython-37m-x86_64-linux-gnu.so'
dropbox: load fq extension '/opt/dropbox/PyQt5.QtGui.cpython-37m-x86_64-linux-gnu.so'
dropbox: load fq extension '/opt/dropbox/PyQt5.QtNetwork.cpython-37m-x86_64-linux-gnu.so'
dropbox: load fq extension '/opt/dropbox/PyQt5.QtWidgets.cpython-37m-x86_64-linux-gnu.so'
dropbox: load fq extension '/opt/dropbox/PyQt5.QtDBus.cpython-37m-x86_64-linux-gnu.so'
Done!

~ $ cat /opt/dropbox/VERSION 
85.4.155

~ $ dropbox status
Checking for changes...
Syncing 15 files
Syncing 15 files...
```

**Comment by nipunn1313** [comment]
Hi,

Thanks for making the time to make a report.

Im going to close this task because this repo is for the open source nautlius extension and command line utility - but do want to to help make sure we can get your problem resolved.

Getting stuck syncing files can manifest for a variety of reasons (eg filesystem permissions issue on parent directory, slow internet connection, gigantic files, out of disk space). From the tray - the dropdown menu can show some additional details of which files are affected to help you solve the issue. If that doesn't help, send me an email and we can take a look at those logs (they're encrypted) and try to get your setup fixed up.

**Comment by nipunn1313** [comment]
there's some documentation on possible reasons - in case that is helpful.
https://help.dropbox.com/installs-integrations/sync-uploads/stuck-syncing
