### ISSUE TITLE
[feature request] proprietary daemon with ppc64le support

### ISSUE THREAD

**Issue by runlevel5** [dropbox/nautilus-dropbox#87]
## Steps to produce
 
```
$ uname -r
5.6.0-0.rc7.git1.2.local.fc33.ppc64le
$ ./dropbox -i
```

Expected:

* Daemon installation works correctly

Actual:

* Unsupported platform

**Comment by nikhilm** [comment]
Is this a feature request to support PowerPC?
The dropbox client does not support running on this architecture and it is unlikely we will support it in the foreseeable future.

**Comment by runlevel5** [comment]
@nikhilm this is a request to support the new OpenPOWER's PPC64LE (not the old Mac PowerPC 32).

**Comment by nikhilm** [comment]
Yes. Sorry, we don't have plans to support any PowerPC architecture right now.
