### ISSUE TITLE
no Fedora 32 repo

### ISSUE THREAD

**Issue by christian-korneck** [dropbox/nautilus-dropbox#90]
Fedora 32 is GA, but there's no Fedora 32 repo for Dropbox yet. After an upgrade from fc31 to fc32:

```
$ dnf repolist Dropbox -v
Errors during downloading metadata for repository 'Dropbox':
  - Status code: 404 for http://linux.dropbox.com/fedora/32/repodata/repomd.xml (IP: 13.35.253.112)
Error: Failed to download metadata for repo 'Dropbox': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```

As the readme says "_the Dropbox desktop app [...] officially supports [...] Fedora 21 or higher_" I guess it should be added?

**Comment by christian-korneck** [comment]
> @changusmc closed this 16 minutes ago

there's a Fedora 32 repo now (thanks)  ... but none for Fedora 33 or 34 (the only supported Fedora versions at the moment).

**Comment by christian-korneck** [comment]
is there any way I could help with packaging for Fedora? If so I might offer to volunteer. Feel free to point me into the right direction.

**Comment by changusmc** [comment]
I apologize for closing this, I didn't mean for that to happen.

**Comment by jamerlan** [comment]
Please provide repos for Fedora 33 and 34

**Comment by ziegenberg** [comment]
There is now a repo for Fedora 32, 33, 34 and even 35: https://linux.dropboxstatic.com/fedora/
So I guess, this is solved then?

**Comment by christian-korneck** [comment]
@ziegenberg yes, I successfully installed Dropbox on Fedora 35 and it worked flawlessly. Totally forgot about this ticket. Guess you never complain when something just works. :-)

Thanks Dropbox team! #close
