### ISSUE TITLE
How to change dropbox folder location

### ISSUE THREAD

**Issue by richard457** [dropbox/nautilus-dropbox#92]
For some use case we want to change dropbox folder to /var/www/folder is there a way to do this? please help me out,

**Comment by nipunn1313** [comment]
You can use a symbolic link from /var/www/folder -> Dropbox if that will work for you.

Eg
```
ln -s /var/www/folder /home/username/Dropbox
```

**Comment by richard457** [comment]
I think symbolic can not work for our use case
